const bcrypt = require('bcrypt');
const img3 = ("./images/author-mangaPic5.png");
const img4 = ("./images/gojo-pic2.png");
const img5 = ("./images/SonicPictures.png");

const data = {
  users: [
    {
      name: "Kadeem",
      email: "adminTest5@gmail.com",
      displayName: "Kassie",
      displayRoleType: "Admin",
      displayImage: "./images/anime-pic3.png",
      greeting: "Welcome I am Kassie Your Admin!",
      password: bcrypt.hashSync("djyeTesting123", 10),
      isAdmin: true,
    },
    {
      name: "Karla",
      email: "admin@gmail.com",
      displayName: "Karla",
      displayRoleType: "Admin",
      displayImage: "./images/anime-pic.png",
      greeting: "Welcome I am Karla Your Admin!",
      password: bcrypt.hashSync("KKTesting1234", 10),
      isAdmin: true,
    },
    {
      name: "Tommy",
      email: "tommy@gmail.com",
      displayName: "Tommy",
      displayRoleType: "User",
      displayImage: img5,
      greeting: "Welcome I am Tommy!",
      password: bcrypt.hashSync("testing123", 10),
      isAdmin: false,
    },
    {
      name: "Sally",
      email: "sally@gmail.com",
      displayName: "Sally",
      displayRoleType: "User",
      displayImage: img3,
      greeting: "Welcome I am Sally!",
      password: bcrypt.hashSync("testing1234", 10),
      isAdmin: false,
    },
    {
      name: "Billy",
      email: "billyTest@gmail.com",
      displayName: "Billy",
      displayRoleType: "User",
      displayImage: img4,
      greeting: "Welcome I am Billy!",
      password: bcrypt.hashSync("testing12345", 10),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: "Wing Zero Gundam EndlessWaltz",
      category: "Custom Gundam",
      image: "./images/products/WingZeroGundam.png",
      price: 320,
      countInStock: 10,
      brand: "Bandai",
      rating: 4.5,
      numReviews: 10,
      description: "high quality Gundam model kit",
    },
    {
      name: "Justice Gundam",
      category: "Custom Gundam",
      image: "./images/products/JusticeGundam.png",
      price: 200,
      countInStock: 20,
      brand: "Bandai",
      rating: 4.0,
      numReviews: 10,
      description: "high quality Gundam model kit",
    },
    {
      name: "StrikeFreedom Gundam",
      category: "Custom Gundam",
      image: "./images/products/StrikeFreedomGundam.png",
      price: 420,
      countInStock: 0,
      brand: "Bandai",
      rating: 4.8,
      numReviews: 17,
      description: "high quality Gundam model kit",
    },
    {
      name: "Strike Rouge Gundam",
      category: "Plastic Model Kit",
      image: "./images/products/StrikeRougueGundam.png",
      price: 98,
      countInStock: 15,
      brand: "Sunrise",
      rating: 4.5,
      numReviews: 14,
      description: "high quality Gundam model kit plastic",
    },
    {
      name: "Buster Gundam",
      category: "Plastic Model Kit",
      image: "./images/products/BusterGundam.png",
      price: 165,
      countInStock: 5,
      brand: "Sunrise",
      rating: 4.5,
      numReviews: 10,
      description: "high quality Gundam model kit plastic",
    },
    {
      name: "Destiny Gundam",
      category: "Custom Gundam",
      image: "./images/products/DestinyGundam.png",
      price: 339,
      countInStock: 12,
      brand: "Bandai",
      rating: 4.5,
      numReviews: 15,
      description: "high quality Gundam model kit",
    },
  ],
};

module.exports = data;